apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-platform.fullname" . }}-config
  labels:
    {{- include "kafka-platform.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.springProfile | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: {{ .Values.kafka.schemaRegistryUrl | quote }}
  SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  SPRING_KAFKA_STREAMS_PROPERTIES_SCHEMA_REGISTRY_URL: {{ .Values.kafka.schemaRegistryUrl | quote }}
