{{- if .Values.pdb.enabled }}
{{- range $name, $svc := .Values.services }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  labels:
    {{- include "kafka-platform.labels" $ | nindent 4 }}
    {{- include "kafka-platform.selectorLabels" (dict "name" $name "root" $) | nindent 4 }}
spec:
  minAvailable: {{ $.Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "kafka-platform.selectorLabels" (dict "name" $name "root" $) | nindent 6 }}
{{- end }}
{{- end }}
