apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-platform.fullname" . }}-secret
  labels:
    {{- include "kafka-platform.labels" . | nindent 4 }}
type: Opaque
data:
  KAFKA_SASL_USERNAME: {{ .Values.secrets.kafkaSaslUsername | b64enc | quote }}
  KAFKA_SASL_PASSWORD: {{ .Values.secrets.kafkaSaslPassword | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
